apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "imanage-integration.fullname" . }}-appsettings
data:
  appsettings.json: |
    {
      "ConsoleApiKey": {{ .Values.consoleApiKey | quote }},
      "IManage": {
        {{- with .Values.imanage }}
        "OAuthTokenUrl": {{ .oAuthTokenUrl | quote }},
        "ApiUrl": {{ .apiUrl | quote }},
        "ClientId": {{ .clientId | quote }},
        "ClientSecret": {{ .clientSecret | quote }},
        "AdminUserName": {{ .adminUserName | quote }},
        "AdminUserPassword": {{ .adminUserPassword | quote }},
        "Library": {{ .library | quote }},
        "DefaultFolderName": {{ .defaultFolderName | quote }},
        {{- end }}
      },
      "Prime": {
        {{- with .Values.evolvePrime }}
        "ApiUrl": {{ .apiUrl | quote }},
        "TokenEndpoint": {{ .tokenEndpoint | quote }},
        "Scope": {{ .scope | quote }},
        "ClientId": {{ .clientId | quote }},
        "ClientSecret": {{ .clientSecret | quote }},
        "SigningKey": {{ .signingKey | quote }},
        "ReceiverUrl": {{ .receiverUrl | quote }},

        "Tenant": {{ .tenant | quote }},
        "ApiKey": {{ .apiKey | quote }}
        {{- end }}
      }
    }